vich_uploader:
    db_driver: orm # Doctrine ORM
    mappings:
        super_hero_image: # Mapping pour Super Héros
            uri_prefix: /uploads/superheroes # Chemin public d'accès aux fichiers
            upload_destination: '%kernel.project_dir%/public/uploads/superheroes' # Emplacement des fichiers
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # Génère des noms uniques pour éviter les conflits
            delete_on_update: true # Supprime l'ancien fichier si un nouveau est uploadé
            delete_on_remove: true # Supprime le fichier si l'entité est supprimée
